### ISSUE TITLE
Getting an error with ./configure --prefix=/usr/local

### ISSUE THREAD

**Issue by Vladinatrix** [rickyrockrat/gnomekeyringtool#1]
I'm getting a syntax error when ./configure is invoked with --prefix=/usr/local

[root@svn7 gnomekeyringtool-master]# ./configure --prefix=/usr/local
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for style of include used by make... GNU
checking dependency style of g++... gcc3
checking for gcc... gcc
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking whether make sets $(MAKE)... (cached) yes
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking stdio.h usability... yes
checking stdio.h presence... yes
checking for stdio.h... yes
checking getopt.h usability... yes
checking getopt.h presence... yes
checking for getopt.h... yes
checking for unistd.h... (cached) yes
checking for an ANSI C-conforming const... yes
checking whether struct tm is in sys/time.h or time.h... time.h
checking for strftime... yes
checking for getpass... yes
checking for strdup... yes
./configure: line 4870: PKG_PROG_PKG_CONFIG: command not found
./configure: line 4872: syntax error near unexpected token `GNOMEKEYRING,'
./configure: line 4872:`PKG_CHECK_MODULES(GNOMEKEYRING, gnome-keyring-1)'

This is on a CentOS 7 system, please let me know what other information about the environment would be useful.

**Comment by rickyrockrat** [comment]
Please try to reconfigure it with autoreconf.
It may mean you don't have pkg-config installed. Here is the problem, I think:
http://stackoverflow.com/questions/17089858/pkg-config-pkg-prog-pkg-config-command-not-found
